import svg4everybody from 'svg4everybody';
import objectFitImages from 'object-fit-images';
import './globalOptions';
import anchor from '../blocks/js-functions/anchor';
import dragscroll from '../blocks/js-functions/dragscroll';
import { freezebuttons } from '../blocks/js-functions/freeze';
import scrollanimation from '../blocks/js-functions/scrollanimation';
import { selects, sliders, datepicker, inputmask, numberinput } from '../blocks/form-elements/form-elements';
import popups from '../blocks/popups/popups';
import scrollbar from '../blocks/scrollbar/scrollbar';
import slider from '../blocks/slider/slider';
import tooltips from '../blocks/tooltip/tooltip';
import tabs from '../blocks/tabs/tabs';
import maps from '../blocks/map/map';
import card from '../blocks/card/card';
import tags from '../blocks/tags/tags';
import filter from '../blocks/filter/filter';
import switcher from '../blocks/switcher/switcher';
import reviews from '../components/reviews/reviews';
import sales from '../pages/sales/sales';
import feedback from '../pages/feedback/feedback';
import comments from '../pages/comments/comments';
import '../blocks/rating/rating';
import '../blocks/accordion/accordion';
import '../blocks/dropdown/dropdown';
import '../blocks/put-block-into-slot/put-block-into-slot';
import '../blocks/sitemap/sitemap';

const $ = window.$;

$(() => {
  svg4everybody();
  objectFitImages();
  anchor();
  dragscroll();
  freezebuttons();
  selects();
  sliders();
  popups();
  scrollbar();
  slider();
  tooltips();
  tabs();
  datepicker();
  inputmask();
  numberinput();
  maps();
  card();
  tags();
  filter();
  switcher();
  reviews();
  sales();
  feedback();
  comments();
  scrollanimation();
});
